<a href="https://colab.research.google.com/github/hatimdeve/python/blob/main/00_tenserflowfundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#intro to tensors 

In [ ]:
#import tensorflow
import tensorflow as tf
print(tf.__version__)


2.8.2


In [ ]:
#create tensors with tf.constant()
scalar =tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check dimentions
scalar.ndim

0

In [ ]:
#create vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#create matrix
matrix=tf.constant([[10,10],[12,12]],dtype=tf.float16)#by default is int we can chnage type by parameter dtype
matrix
matrix.ndim

2

In [ ]:
#create tensor
tensor=tf.constant([[[10,10],[12,25]],[[10,10],[14,12]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[10, 10],
        [12, 25]],

       [[10, 10],
        [14, 12]]], dtype=int32)>

In [ ]:
#create tensor with tf.variable()
changeable_tensor=tf.Variable([10,10])
unchangeable_tensor=tf.constant([10,10])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [ ]:
#we can change the varianble tansen with assign but the constant we cant
changeable_tensor[0].assign(7) 
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
#creating random tensor
random1=tf.random.Generator.from_seed(7)
random1=random1.normal(shape=(3,2))
random2=tf.random.Generator.from_seed(7)
random2=random2.normal(shape=(3,2))
random1,random2,random1==random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.2878567 ],
        [-0.8757901 , -0.08857017],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.2878567 ],
        [-0.8757901 , -0.08857017],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
#shuufle the tensor

In [ ]:
not_suffled=tf.constant([[6,10],[4,5],[8,6]])
not_suffled


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6, 10],
       [ 4,  5],
       [ 8,  6]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_suffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8,  6],
       [ 4,  5],
       [ 6, 10]], dtype=int32)>

In [ ]:
# create tensor of one
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create tensor of zero
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#turn numpy array to tensor
import numpy as np
a=np.arange(1,25,dtype=np.int32)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
b=tf.constant(a,shape=(2,3,4))
b

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
#getting info from tensors
tensor=tf.zeros([2,3,4,5])
tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
tensor.shape,tensor.ndim,tf.size(tensor).numpy(),tensor[0]

(TensorShape([2, 3, 4, 5]),
 4,
 120,
 <tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
 array([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=float32)>)

In [ ]:
#indexinf tensors
tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
tensor[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#create a rank 2 tensor
tensor2=tf.constant([[10,7],[3,4]])

In [ ]:
#add extra dimension
tf.expand_dims(tensor2,axis=-1)# means empand the final axis 

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#manipulation tensors(basic operation)
tensor=tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#we can use the tensor flow function
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
#matrix multiplication
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor* tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
#the correct operation for mul matrix is '@'
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#reshape matrix
tensor=tf.constant([[10,7],[3,4],[5,1]])
tf.reshape(tensor,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  7,  3],
       [ 4,  5,  1]], dtype=int32)>

In [ ]:
#transposer
tf.transpose(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  3,  5],
       [ 7,  4,  1]], dtype=int32)>

In [ ]:
#changing data type
tensor=tf.constant([[10,7],[3,4],[5,1]])
d=tf.cast(tensor,dtype=tf.float16)
tensor,d

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 5,  1]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[10.,  7.],
        [ 3.,  4.],
        [ 5.,  1.]], dtype=float16)>)

In [ ]:
#agrégation tensors
d=tf.constant([-7,-10])

In [ ]:
#get the absolute
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
#agrégation opération 
e=tf.constant(np.random.randint(0,100,size=50))
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([96, 16, 96, 11, 96,  0, 15,  1, 78, 12, 93, 54, 24, 56, 38, 32, 31,
       14, 51, 38, 51, 37, 93, 79, 71, 57, 21, 41,  9,  7, 20, 30, 42, 77,
       76, 57, 87,  7, 50, 62, 97, 60, 59, 78, 81,  8, 40, 64, 77, 58])>

In [ ]:
#find mean
tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [ ]:
#find variance 
import tensorflow_probability as tfp
tfp.stats.variance(e)

<tf.Tensor: shape=(), dtype=int64, numpy=863>

In [ ]:
tf.math.reduce_variance(tf.cast(e,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=862.83844>

In [ ]:
#find the standard deviation
tf.math.reduce_std(tf.cast(e,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.374111>

In [ ]:
#finding position of max and min
f=tf.random.uniform([50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.9256557 , 0.2568636 , 0.861287  , 0.09648132, 0.9021479 ,
       0.08919621, 0.12253678, 0.34183872, 0.17881584, 0.14536667,
       0.4902743 , 0.6040206 , 0.00164723, 0.5756427 , 0.90879285,
       0.33926833, 0.78277373, 0.07431972, 0.18423676, 0.2959262 ,
       0.20065641, 0.25143552, 0.8386421 , 0.9509078 , 0.77134025,
       0.9708636 , 0.0545361 , 0.20997036, 0.51690066, 0.07624471,
       0.1988908 , 0.5015513 , 0.9023589 , 0.10599101, 0.67463696,
       0.45146787, 0.8598558 , 0.43234253, 0.8179493 , 0.45608962,
       0.05629158, 0.58011055, 0.6009213 , 0.16283143, 0.21293843,
       0.6184372 , 0.04974854, 0.3891114 , 0.41546762, 0.5466323 ],
      dtype=float32)>

In [ ]:
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=25>

In [ ]:
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9708636>

In [ ]:
tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9708636>

In [ ]:
#squeezing tensors(eliminate 1 dim in shapes)
tf.random.set_seed(42)
g=tf.constant(tf.random.uniform([50]),shape=(1,1,1,1,50))
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
squeeze=tf.squeeze(g)
squeeze

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#one-hot encoding tensors
list1=[0,1,2,3]
tf.one_hot(list1,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#specify custom valuees for ine hot encoding
tf.one_hot(list1,depth=4,on_value="i love u",off_value="no")


<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'i love u', b'no', b'no', b'no'],
       [b'no', b'i love u', b'no', b'no'],
       [b'no', b'no', b'i love u', b'no'],
       [b'no', b'no', b'no', b'i love u']], dtype=object)>

In [ ]:
#tensorflow and numpy
v=tf.constant(np.array([3.,7.,10.]))
v

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
np.array(v),type(np.array(v))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
v.numpy(),type(v.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# default type of each are diffrent
numpy=tf.constant(np.array([3.,7.,10.]))
tensor =tf.constant([3.,7.,10.])
numpy.dtype,tensor.dtype

(tf.float64, tf.float32)

In [ ]:
#finding access tp gpu's
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Fri Oct  7 22:23:13 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P0    28W /  70W |    286MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------